- hosts: all
  vars:
    machine:
      username: '{{ ansible_user }}'
      password: '{{ ansible_password }}'

  tasks:
    - debug:
        var: machine.username
    - debug:
        var: machine.password
