---
- name: BIG-IP SETUP
  hosts: tag_lb
  connection: local
  gather_facts: false

  tasks:
    - name: Setting up provider values
      set_fact:
       provider:
        server: "{{ ansible_host }}"
        server_port: "8443"
        validate_certs: "False"

    - name: ADD VIRTUAL SERVER
      bigip_virtual_server:
        provider: "{{ provider }}"
        name: "vip"
        destination: "{{ private_ip_address }}"
        port: "443"
        enabled_vlans: "all"
        all_profiles: ['http','clientssl','oneconnect']
        pool: "http_pool"
        snat: "Automap"

    - name: PRINT OUT WEB VIP FOR F5
      debug:
        msg: "The VIP (Virtual IP) is https://{{ ansible_host }}"
...
