---
- name: AS3
  hosts: tag_lb
  connection: local
  gather_facts: false

  vars:
    poolMembers: "{{ groups['tag_webservers'] }}"

  #vars_prompt:
  #  - name: "tenantName"
  #    prompt: "Enter the Tenant name:"
  #    private: no
  #    default: "WorkshopExample"

  tasks:
    - name: Push AS3
      uri:
        url: "https://{{ ansible_host }}:8443/mgmt/shared/appsvcs/declare"
        method: POST
        body: "{{ lookup('template','as3_template.j2', split_lines=False) }}"
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ f5UserName }}"
        password: "{{ f5Password }}"
        validate_certs: false
...
