---
- name: AS3
  hosts: tag_lb
  connection: local
  gather_facts: false

#  vars_prompt:
#    - name: "tenantName"
#      prompt: "Enter the Tenant name:"
#      private: no
#      default: "WorkshopExample"

  tasks:
  - name: Remove Tenant AS3
    uri:
      url: "https://{{ ansible_host }}:8443/mgmt/shared/appsvcs/declare/{{ tenantName }}"
      method: DELETE
      status_code: 200
      timeout: 300
      body_format: json
      force_basic_auth: true
      user: "admin"
      password: "Mys1dlabspw!"
      validate_certs: false
...
